### PR TITLE
PR for Lesson: Jupyter

### PR DESCRIPTION
**Pull request by ceholden**
Addresses #14. Sorry I've forgotten to pull it back here for so long!

One question to address --  how do we feel about submodules? I added [`reveal.js`](https://github.com/hakimel/reveal.js/) as a submodule in the root of this repo because it made things easier for me and I can see us using it in the future. It will work on the `gh-pages` side of things so we could have reveal.js slides on our site and would also come in useful for other lessons (like a lesson on `reveal.js` itself). See commit 6d91aebe52be33626ac4f497c6f6fdfa329e9a08 for the addition.

Just a reminder as I didn't get this down until recently, if you clone a repo with a submodule, you need a:

```
git submodule update --init --recursive
```

before you start. You can also just pull with a `git clone --recursive`.

If we don't want to add the submodule, I'll change it in my repo and update the PR.

### CODE REVIEW

**Comment by tomhohenstein** [comment]
So this is interesting. You're proposing, I hope I have this right, that we add a submodule in our repo for other repos - i.e. reveal.js. That will allow us to keep all our documentation in one spot and give us the ability to update it as these projects move forward, right?

The only downside is it is a little more complex to handle in git.

This could be a great addition to the Jekyll lesson too.

**Comment by ceholden** [comment]
So after writing the text below, I decided to nuke my fork that had the `reveal.js` submodule and just add the lesson content in 1 commit. I think the decision for adding the submodule should be it's own issue, so I've added a bit of text to the lesson README about needing to add `reveal.js` before the slides can work.

I'd say merge this one commit PR (unless I messed something up) and we'll think on submodules later. I'd be happy to do a demo of `reveal.js`, including how turn Markdown into `reveal.js` slides.

---

I think that's a pretty good set of pros/cons about including the submodule. Instead of simply copying all of the JS/CSS/etc. from reveal.js, the submodule ties it to a specific commit from that project with the ability to go back/forward in their project history, just as you say. 

The other nice thing that I use reveal.js as a submodule for is that Github will clone reveal.js when it serves our Github pages. I'm not sure it's the thing to do for the library website, but we could actually serve the slides via the Github pages. For example, in my local fork of the repo I can access the slides at `http://localhost:4000/lessons/jupyter/slides/1_introduction.html` after running `bundle exec jekyll serve -w`.

I'm having second thoughts though about the need for it since we're trying to emphasize live demos or work alongs rather than standard presentations. It's nice for a quick intro, as I used it, but that content can also be accessed just as plain markdown.

**Comment by tomhohenstein** [comment]
all great ideas - I added a new issue for the submodule conversation. 

I'm also not opposed to using slides to talk about basics, however, we do want to avoid _long_ slide shows. More tinkering less lecturing. I do like the idea of serving up lessons via GitHub Pages. I also think that is a generally great lesson to learn.

**Comment by tomhohenstein** [comment]
I reopened this because reveal.js is only a pointer to another version of reveal.js. Did you use the default reveal.js?

**Comment by ceholden** [comment]
Thanks for catching that. I forgot I had used a symbolic link in the Makefile to point to the reveal.js folder rather than pointing to it directly.

In the `lessons/jupyter/slides/Makefile`:

``` bash
### Location of reveal.js
RJS = reveal.js
```

points to the [symbolic link, `reveal.js`](https://github.com/ceholden/studyGroup/blob/acc9355061d060bc84991e90c2ecf7909919a77d/lessons/jupyter/slides/reveal.js), which in turn points to `reveal.js` within the root of this repo. You could edit it to be:

``` bash
### Location of reveal.js
RJS = ../../../reveal.js
```

and it would work assuming you've copied or added reveal.js as a submodule into the root of this repo. No specific reveal.js was used -- just whatever was latest in master at the time.

**Comment by ceholden** [comment]
I'm a little confused about what happened in 0d1d6ec2b61909bbc78778d72f4794ee71dfe21f and onward. Looks like you added a simple unversioned copy of reveal to the `_site` folder? Are we supposed to let jeykll do its thing with the `_site` folder since this is what is auto-generated and hosted from the rest of the repo? The main jeykll repo adds `_site` to their [`.gitignore`](https://github.com/jekyll/jekyll/blob/master/.gitignore), for example, so it's never included.

What seems to me to be easier to work with is to have one copy of `reveal.js` in a common location that lessons can point to rather than one copy per lesson. Take a look at [my personal jekyll based website that uses submodules for `reveal.js`](https://github.com/ceholden/ceholden.github.io) as an example. The submodule is retrieved as part of the rest of the repo and then Github pages via jeykll builds everything and sticks it in `_site`, including the copy of `reveal.js`. Seems to work reasonably well and I've been able to upgrade `reveal.js` to the latest version once so far without issue.

I don't think I was very clear about my previous suggestions. I'll take another stab at what I was proposing:
1. Chris should add info into lesson README about `reveal.js` being a requirement to run the slides (done -- [link](https://github.com/bulib/studyGroup/tree/gh-pages/lessons/jupyter#overview))
2. Accept PR of jupyter lesson without a copy of `reveal.js`
3. Discuss issues surrounding submodules and `reveal.js` in #21 
4. If #21 raises no better alternative or objections, add `reveal.js` as a submodule to the root of this repo and add some reminder documentation about needing to run `git clone --recursive [repo url]` when cloning or `git submodule update --init` after cloning to pull the `reveal.js` submodule
5. Update `jupyter` slides to link against newly added `reveal.js`
6. Future lessons that want to use `reveal.js` can link against `reveal.js` submodule in root of this repo

**Comment by tomhohenstein** [comment]
whew - wow what a small hassle accidentally moving the wrong folder was. sorry about all that. I wanted to add the css, js, and other folders so that your [presentation would be available](http://study.bu.edu/lessons/jupyter/slides/1_introduction.html) and could serve as a module for discussion. But, by grabbing the git repo version of reveal.js (and not the zip files that I wanted) I stumbled right into the submodule issue you told me about (which, then took me a bit to figure out how to remove it on both locally and on github). 

But I think we are all set now. The site builds, we have a demo presentation to discuss, and your lesson has been added. I think we can move the rest of this to #21. 

Again, sorry about that.

**Comment by ceholden** [comment]
Great!

**Pull request merged**
